import numpy as np
print("Matrix 1")
R = int(input("Enter the number of rows :"))
C = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
matrix = np.array(entries).reshape(R, C)
print("Matrix 2")
R1= int(input("Enter the number of rows:"))
C1 = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries1 = list(map(int, input().split()))
matrix1 = np.array(entries).reshape(R, C)
matrix2 = np.array(entries1).reshape(R1, C1)
print(matrix1+matrix2)

